# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# DefineProjection_20180725.py
# Created on: 2018-07-25 09:50:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env 
import os

# Set environment settings
env.workspace = r"xxxxxxxxxxxxxxxxxxxxxxxxx\imgs"

# Get and print a list of GRIDs from the workspace
rasters = arcpy.ListRasters("*", "IMG")
print(rasters)

for raster in rasters:
    print(raster)
    name = arcpy.Describe(raster).baseName #get metadata out of an object; returns a "describe object"
    raster__2_ = raster
    
    # Process: Define Projection
    arcpy.DefineProjection_management(raster, "PROJCS['NAD_1983_UTM_Zone_15N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-93.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]")

    print('Finished converting {}\n'.format(name))
